<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PV-8" ignored="1" name="简单测试" tests="19" failures="3" timestamp="31 十二月 2020 15:52:34 GMT" time="0.038" errors="0">
  <testcase name="testCase0" time="0.007" classname="test.sample.CaseRunTest"/>
  <testcase name="testCase1" time="0.0" classname="test.sample.CaseRunTest"/>
  <testcase name="testCase2" time="0.0" classname="test.sample.CaseRunTest"/>
  <testcase name="testAdd2" time="0.0" classname="test.sample.DataProviderTest"/>
  <testcase name="testAdd2" time="0.0" classname="test.sample.DataProviderTest"/>
  <testcase name="testAdd2" time="0.0" classname="test.sample.DataProviderTest">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;6&amp;gt; but was:&amp;lt;7&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<6> but was:<7>
at test.sample.DataProviderTest.testAdd2(DataProviderTest.java:21)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testAdd2 -->
  <testcase name="testAdd1" time="0.0" classname="test.sample.DependentMethodsTest">
    <failure type="org.testng.TestException" message="
Expected exception of type class java.lang.RuntimeException but got java.lang.AssertionError: expected:&amp;lt;3&amp;gt; but was:&amp;lt;4&amp;gt;">
      <![CDATA[org.testng.TestException: 
Expected exception of type class java.lang.RuntimeException but got java.lang.AssertionError: expected:<3> but was:<4>
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: expected:<3> but was:<4>
at test.sample.DependentMethodsTest.testAdd1(DependentMethodsTest.java:11)
... 14 more
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testAdd1 -->
  <testcase name="testAdd1" time="0.0" classname="test.sample.DependGroupsTest">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;5&amp;gt; but was:&amp;lt;4&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<5> but was:<4>
at test.sample.DependGroupsTest.testAdd1(DependGroupsTest.java:11)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testAdd1 -->
  <testcase name="testAdd2" time="0.0" classname="test.sample.DependGroupsTest"/>
  <testcase name="testCase" time="0.0" classname="test.sample.FirstTest"/>
  <testcase name="testCase1" time="0.001" classname="test.sample.FixtureTest"/>
  <testcase name="testCase2" time="0.0" classname="test.sample.FixtureTest"/>
  <testcase name="testCase4" time="0.0" classname="test.sample.GroupsTest"/>
  <testcase name="testCase5" time="0.0" classname="test.sample.GroupsTest"/>
  <testcase name="testCase6" time="0.0" classname="test.sample.GroupsTest"/>
  <testcase name="testCase7" time="0.0" classname="test.sample.GroupsTest"/>
  <testcase name="TestCase3" time="0.001" classname="test.sample.SecondTest"/>
  <testcase name="testAdd2" time="0.0" classname="test.sample.DependentMethodsTest">
    <skipped/>
  </testcase> <!-- testAdd2 -->
  <testcase name="testAdd3" time="0.0" classname="test.sample.DependGroupsTest">
    <skipped/>
  </testcase> <!-- testAdd3 -->
  <testcase name="testAdd1" time="0.0" classname="test.sample.ParametersTest">
    <ignored/>
  </testcase> <!-- testAdd1 -->
</testsuite> <!-- 简单测试 -->
